#!/usr/bin/env python
import sys
import os

def find_file(eid, field):
    filename = '_'.join([eid, field])
    with open("/om4/project/biobank/all_files.txt") as fp:
        for line in fp.readlines():
            if filename in line:
                return line.strip().replace("./", "/om4/project/biobank/")
    return None


def get_fields(filename):
    fields = None
    with open(filename) as fp:
        fields = [val.strip().split() for val in fp.readlines()]
    return fields


def in_cwd(eid, field):
    ukbfile = '_'.join([eid, field])
    for dp, dn, files in os.walk(os.getcwd()):
        dn.clear() # no need for recursing
        for filename in files:
            if ukbfile in filename:
                return True
    return False
    

if __name__ == "__main__":
   print(sys.argv)
   keyfile = [val for val in sys.argv[1:] if val.startswith("-a")].pop()
   tmploc = [val for val in sys.argv[1:] if val.startswith("-o")].pop()
   fields = get_fields('.ukbbatch')
   for eid, field in fields:
       if in_cwd(eid, field):
           continue
       filename = find_file(eid, field)
       if filename is None:
           print(f"Missing {eid} {field}")
           with open("/om4/project/biobank/ukbmissing", "at") as fp:
               fp.writelines(f"{eid} {field}\n")
           #args = ['-v', keyfile, tmploc, f"-e{eid}", f"-d{field}"]
           #os.system(' '.join(["/om4/project/biobank/ukb/bin/ukbfetch"] + args))
       else:
           print(f"Found {filename}: moving")
           from shutil import copyfile, move
           #copyfile(filename, os.path.basename(filename))
           #move(filename, os.getcwd())
           move(filename, os.path.basename(filename))
